### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by fredattack** [orykami/laravel-ovh-sms#5]
Hi, 
I try to install you package on a  laravel 8 application, but receive this error 👍 
[InvalidArgumentException]                                                                                                                                                                        
```
  Could not find a matching version of package orykami/laravel-ovh-sms. Check the package spelling, your version constraint and that the package is available in a stability which matches your mi  
  nimum-stability (dev).   
```

Do you have any idea of what append? 

Regards.

**Comment by orykami** [comment]
@fredattack 
My apologies for the response delay :/
You have this error because this repository isn't packaged with composer natively. To use it with composer, you must add this section to your composer.json (private repository) : 

```json composer.json
{
"repositories": [
    {
      "name": "orykami/laravel-ovh-sms",
      "type": "git",
      "url": "https://github.com/orykami/laravel-ovh-sms"
    }
  ]
}
```

And add package definition like this :
```json
{
  "require": {
    "orykami/laravel-ovh-sms": "^1.0.3",
  }
}
```

I hope it will help you ! 👍
